### ISSUE TITLE
freezing of model fails if eager mode is disabled

### ISSUE THREAD

**Issue by eduand-alvarez** [oneapi-src/demand-forecasting#3]
In the training script, you seem to be disabling eager mode: tf.compat.v1.disable_eager_execution()

If you disable eager mode, the line below fails. 

frozen_model = convert_variables_to_constants_v2(concrete_function) 

The error you get is numpy() is only available when eager execution is enabled.

Running on  4th Gen Xeon CPU

My package version: 
pandas==1.4.1
scikit-learn==1.0.1
tensorflow==2.10.0

**Comment by aagalleg** [comment]
Hello. 
We made some updates to the repo. Check if the problem was solved with the new updates.

**Comment by aagalleg** [comment]
Issue will be closed due to inactivity.
